name: flutter_local_notification
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.6.0
  timezone: ^0.8.0
  rxdart: ^0.26.0
  intl: ^0.18.0
  google_maps_flutter: ^2.2.2
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_svg: ^1.1.6
  screens: ^2.5.0
  geocoder2: ^1.4.0
  url_launcher: ^6.1.7
  torch_light: ^1.0.0
  vibration: ^1.7.6
  auto_size_text: ^3.0.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  google_fonts: ^3.0.1
  audioplayers: ^1.1.1
  geolocator: ^9.0.2
  google_api_headers: ^1.5.0
  google_maps_webservice: ^0.0.19
  awesome_snackbar_content: ^0.1.0
  flutter_google_places: ^0.3.0
  flame_audio: ^1.3.3
  auto_start_flutter: ^0.1.1
 
  highlight_text: ^1.6.0
  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/pick.png
    - assets/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages